import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

// Common Node.js + browser globals so no-undef doesn't fire on builtins
const nodeGlobals = {
  process: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  global: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setImmediate: 'readonly',
  clearImmediate: 'readonly',
  queueMicrotask: 'readonly',
  console: 'readonly',
};

const webGlobals = {
  React: 'readonly',
  JSX: 'readonly',
  fetch: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  Headers: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  FormData: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  HTMLElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLFormElement: 'readonly',
  HTMLDivElement: 'readonly',
  HTMLAnchorElement: 'readonly',
  HTMLImageElement: 'readonly',
  HTMLSpanElement: 'readonly',
  Event: 'readonly',
  EventTarget: 'readonly',
  MouseEvent: 'readonly',
  KeyboardEvent: 'readonly',
  FocusEvent: 'readonly',
  InputEvent: 'readonly',
  SubmitEvent: 'readonly',
  ClipboardEvent: 'readonly',
  DragEvent: 'readonly',
  PointerEvent: 'readonly',
  TouchEvent: 'readonly',
  WheelEvent: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  MutationObserver: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  EventSource: 'readonly',
  WebSocket: 'readonly',
  MessageEvent: 'readonly',
  CloseEvent: 'readonly',
  ErrorEvent: 'readonly',
  CustomEvent: 'readonly',
  RequestInit: 'readonly',
  ResponseInit: 'readonly',
  HeadersInit: 'readonly',
  BodyInit: 'readonly',
  RequestInfo: 'readonly',
  document: 'readonly',
  window: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  crypto: 'readonly',
  performance: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FileList: 'readonly',
  ReadableStream: 'readonly',
  WritableStream: 'readonly',
  TextDecoder: 'readonly',
  TextEncoder: 'readonly',
  btoa: 'readonly',
  atob: 'readonly',
  structuredClone: 'readonly',
};

/** @type {import('eslint').Linter.Config[]} */
export default [
  js.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        projectService: false,
      },
      globals: {
        ...nodeGlobals,
        ...webGlobals,
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs['recommended'].rules,
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/consistent-type-imports': [
        'warn',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // Disable rules that require full type information
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      // Allow console in server/API code
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      // TypeScript handles redeclaration — const+type sharing a name is valid TS
      'no-redeclare': 'off',
      '@typescript-eslint/no-redeclare': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      '.next/**',
      '.turbo/**',
      'coverage/**',
      '*.generated.ts',
      'eslint.config.mjs',
    ],
  },
];
