import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { z } from 'zod';
import { sql } from 'drizzle-orm';
import type { TenantContext } from '../middleware/tenant-context.js';

export const documentTemplatesRouter = new Hono<{ Variables: TenantContext }>();

// ── Helpers ───────────────────────────────────────────────────

/** Extract unique {{variableName}} tokens from HTML body */
function extractVariables(htmlBody: string): string[] {
  const regex = /\{\{(\w+)\}\}/g;
  const names = new Set<string>();
  let match: RegExpExecArray | null;
  while ((match = regex.exec(htmlBody)) !== null) {
    names.add(match[1]!);
  }
  return Array.from(names);
}

/** Merge auto-extracted variable names with any explicitly provided definitions */
function mergeVariables(
  htmlBody: string,
  explicit: Array<{ name: string; label?: string; defaultValue?: string; required?: boolean }>,
): Array<{ name: string; label: string; defaultValue?: string; required?: boolean }> {
  const extracted = extractVariables(htmlBody);
  const explicitMap = new Map(explicit.map((v) => [v.name, v]));

  return extracted.map((name) => {
    const def = explicitMap.get(name);
    return {
      name,
      label: def?.label ?? name,
      ...(def?.defaultValue !== undefined ? { defaultValue: def.defaultValue } : {}),
      ...(def?.required !== undefined ? { required: def.required } : {}),
    };
  });
}

/** Wrap inner HTML body in a full A4-print-ready HTML document */
function wrapHtml(name: string, innerHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(name)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #1a1a1a;
      background: #fff;
      padding: 20mm;
    }
    h1, h2, h3 { font-family: Georgia, serif; margin-bottom: 0.5em; }
    h1 { font-size: 22pt; letter-spacing: 0.05em; }
    h2 { font-size: 16pt; }
    h3 { font-size: 13pt; }
    p { margin-bottom: 0.4em; }
    .doc-header { margin-bottom: 24pt; border-bottom: 2px solid #1a1a1a; padding-bottom: 12pt; }
    .doc-parties { display: flex; gap: 40pt; margin-bottom: 24pt; }
    .doc-parties > div { flex: 1; }
    .doc-table { width: 100%; border-collapse: collapse; margin-bottom: 20pt; }
    .doc-table th, .doc-table td {
      border: 1px solid #ccc;
      padding: 6pt 8pt;
      text-align: left;
    }
    .doc-table th { background: #f5f5f5; font-weight: bold; }
    .doc-totals { text-align: right; margin-bottom: 20pt; }
    .doc-totals p { margin-bottom: 4pt; }
    .doc-notes { font-style: italic; color: #555; margin-top: 16pt; }
    .doc-signature-block { display: flex; gap: 40pt; margin-top: 40pt; }
    .doc-signature-block > div { flex: 1; border-top: 1px solid #1a1a1a; padding-top: 8pt; }
    .veska-footer {
      margin-top: 40pt;
      padding-top: 8pt;
      border-top: 1px solid #ddd;
      font-size: 9pt;
      color: #888;
      text-align: center;
    }
    @media print {
      body { margin: 0; padding: 0; }
      .veska-footer { position: fixed; bottom: 0; left: 0; right: 0; }
    }
    @page { size: A4; margin: 20mm; }
  </style>
</head>
<body>
  <main>
    ${innerHtml}
  </main>
  <footer class="veska-footer">Generated by Veska ERP &mdash; ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</footer>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/** Substitute all {{variableName}} occurrences with provided values */
function substituteVariables(htmlBody: string, values: Record<string, string>): string {
  return htmlBody.replace(/\{\{(\w+)\}\}/g, (_, name: string) => values[name] ?? '');
}

// ── Built-in seed templates ────────────────────────────────────

const SEED_TEMPLATES = [
  {
    name: 'Standard Invoice',
    type: 'invoice',
    description: 'Default invoice template with line items, tax, and totals.',
    htmlBody: `<div class="doc-header">
  <h1>INVOICE</h1>
  <p>Invoice #: {{invoiceNumber}}</p>
  <p>Date: {{issueDate}}</p>
  <p>Due Date: {{dueDate}}</p>
</div>
<div class="doc-parties">
  <div><strong>From:</strong><br>{{companyName}}<br>{{companyAddress}}</div>
  <div><strong>To:</strong><br>{{clientName}}<br>{{clientAddress}}</div>
</div>
<table class="doc-table">
  <thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead>
  <tbody><tr><td>{{lineItem1Description}}</td><td>{{lineItem1Qty}}</td><td>{{lineItem1Rate}}</td><td>{{lineItem1Amount}}</td></tr></tbody>
</table>
<div class="doc-totals">
  <p>Subtotal: {{subtotal}}</p>
  <p>Tax ({{taxRate}}%): {{taxAmount}}</p>
  <p><strong>Total: {{total}}</strong></p>
</div>
<p class="doc-notes">{{notes}}</p>`,
    isDefault: true,
  },
  {
    name: 'Standard Quote',
    type: 'quote',
    description: 'Default quote/proposal template with line items and validity date.',
    htmlBody: `<div class="doc-header">
  <h1>QUOTE</h1>
  <p>Quote #: {{quoteNumber}}</p>
  <p>Date: {{issueDate}}</p>
  <p>Valid Until: {{validUntil}}</p>
</div>
<div class="doc-parties">
  <div><strong>From:</strong><br>{{companyName}}<br>{{companyAddress}}</div>
  <div><strong>To:</strong><br>{{clientName}}<br>{{clientAddress}}</div>
</div>
<table class="doc-table">
  <thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead>
  <tbody><tr><td>{{lineItem1Description}}</td><td>{{lineItem1Qty}}</td><td>{{lineItem1Rate}}</td><td>{{lineItem1Amount}}</td></tr></tbody>
</table>
<div class="doc-totals">
  <p>Subtotal: {{subtotal}}</p>
  <p>Tax ({{taxRate}}%): {{taxAmount}}</p>
  <p><strong>Total: {{total}}</strong></p>
</div>
<p class="doc-notes">{{notes}}</p>`,
    isDefault: true,
  },
  {
    name: 'Standard Contract',
    type: 'contract',
    description: 'Simple contract template with terms and signature blocks.',
    htmlBody: `<div class="doc-header">
  <h1>{{contractTitle}}</h1>
  <p>Effective Date: {{effectiveDate}}</p>
</div>
<div class="doc-parties">
  <div><strong>Party A:</strong><br>{{partyA}}</div>
  <div><strong>Party B:</strong><br>{{partyB}}</div>
</div>
<h2>Terms &amp; Conditions</h2>
<p>{{terms}}</p>
<div class="doc-signature-block">
  <div>
    <p><strong>Party A Signature</strong></p>
    <p>{{signatureA}}</p>
  </div>
  <div>
    <p><strong>Party B Signature</strong></p>
    <p>{{signatureB}}</p>
  </div>
</div>`,
    isDefault: true,
  },
];

// ── Template CRUD ──────────────────────────────────────────────

const variableDefSchema = z.object({
  name: z.string(),
  label: z.string().optional(),
  defaultValue: z.string().optional(),
  required: z.boolean().optional(),
});

const templateCreateSchema = z.object({
  name: z.string().min(1),
  type: z.enum(['invoice', 'quote', 'purchase-order', 'contract', 'receipt', 'custom']),
  description: z.string().optional(),
  htmlBody: z.string().default(''),
  variables: z.array(variableDefSchema).optional().default([]),
  isDefault: z.boolean().optional().default(false),
});

const templateUpdateSchema = templateCreateSchema.partial();

// GET /document-templates
documentTemplatesRouter.get('/', async (c) => {
  const { db, tenantId } = c.get('tenantCtx');
  const type = c.req.query('type');

  let result;
  if (type) {
    result = await db.execute(sql`
      SELECT * FROM "documentTemplates"
      WHERE "tenantId" = ${tenantId}
        AND type = ${type}
      ORDER BY "createdAt" DESC
    `);
  } else {
    result = await db.execute(sql`
      SELECT * FROM "documentTemplates"
      WHERE "tenantId" = ${tenantId}
      ORDER BY "createdAt" DESC
    `);
  }

  return c.json({ templates: result.rows ?? [] });
});

// POST /document-templates/seed  — must be before /:id
documentTemplatesRouter.post('/seed', async (c) => {
  const { db, tenantId } = c.get('tenantCtx');

  // Check if any templates already exist for this tenant
  const existing = await db.execute(sql`
    SELECT id FROM "documentTemplates"
    WHERE "tenantId" = ${tenantId}
    LIMIT 1
  `);

  if ((existing.rows ?? []).length > 0) {
    return c.json({ seeded: false, message: 'Templates already exist for this tenant' });
  }

  const seeded: unknown[] = [];
  for (const tpl of SEED_TEMPLATES) {
    const vars = mergeVariables(tpl.htmlBody, []);
    const result = await db.execute(sql`
      INSERT INTO "documentTemplates" (
        "tenantId", name, type, description, "htmlBody", variables, "isDefault"
      ) VALUES (
        ${tenantId},
        ${tpl.name},
        ${tpl.type},
        ${tpl.description},
        ${tpl.htmlBody},
        ${JSON.stringify(vars)}::jsonb,
        ${tpl.isDefault}
      )
      RETURNING *
    `);
    const row = (result.rows ?? [])[0];
    if (row) seeded.push(row);
  }

  return c.json({ seeded: true, count: seeded.length, templates: seeded }, 201);
});

// GET /document-templates/rendered  — must be before /:id
documentTemplatesRouter.get('/rendered', async (c) => {
  const { db, tenantId } = c.get('tenantCtx');
  const entityType = c.req.query('entityType');
  const entityId = c.req.query('entityId');

  let result;
  if (entityType && entityId) {
    result = await db.execute(sql`
      SELECT * FROM "generatedDocuments"
      WHERE "tenantId" = ${tenantId}
        AND "entityType" = ${entityType}
        AND "entityId" = ${entityId}
      ORDER BY "createdAt" DESC
    `);
  } else if (entityType) {
    result = await db.execute(sql`
      SELECT * FROM "generatedDocuments"
      WHERE "tenantId" = ${tenantId}
        AND "entityType" = ${entityType}
      ORDER BY "createdAt" DESC
    `);
  } else {
    result = await db.execute(sql`
      SELECT * FROM "generatedDocuments"
      WHERE "tenantId" = ${tenantId}
      ORDER BY "createdAt" DESC
    `);
  }

  return c.json({ documents: result.rows ?? [] });
});

// GET /document-templates/rendered/:docId
documentTemplatesRouter.get('/rendered/:docId', async (c) => {
  const { db, tenantId } = c.get('tenantCtx');
  const docId = c.req.param('docId');

  const result = await db.execute(sql`
    SELECT * FROM "generatedDocuments"
    WHERE id = ${docId}
      AND "tenantId" = ${tenantId}
    LIMIT 1
  `);

  const row = (result.rows ?? [])[0];
  if (!row) return c.json({ error: 'Not found' }, 404);
  return c.json(row);
});

// POST /document-templates
documentTemplatesRouter.post('/', zValidator('json', templateCreateSchema), async (c) => {
  const { db, tenantId } = c.get('tenantCtx');
  const body = c.req.valid('json');

  const vars = mergeVariables(body.htmlBody, body.variables);

  const result = await db.execute(sql`
    INSERT INTO "documentTemplates" (
      "tenantId", name, type, description, "htmlBody", variables, "isDefault"
    ) VALUES (
      ${tenantId},
      ${body.name},
      ${body.type},
      ${body.description ?? null},
      ${body.htmlBody},
      ${JSON.stringify(vars)}::jsonb,
      ${body.isDefault ?? false}
    )
    RETURNING *
  `);

  const row = (result.rows ?? [])[0];
  if (!row) return c.json({ error: 'Failed to create template' }, 500);
  return c.json(row, 201);
});

// GET /document-templates/:id
documentTemplatesRouter.get('/:id', async (c) => {
  const { db, tenantId } = c.get('tenantCtx');
  const id = c.req.param('id');

  const result = await db.execute(sql`
    SELECT * FROM "documentTemplates"
    WHERE id = ${id}
      AND "tenantId" = ${tenantId}
    LIMIT 1
  `);

  const row = (result.rows ?? [])[0];
  if (!row) return c.json({ error: 'Not found' }, 404);
  return c.json(row);
});

// PUT /document-templates/:id
documentTemplatesRouter.put('/:id', zValidator('json', templateUpdateSchema), async (c) => {
  const { db, tenantId } = c.get('tenantCtx');
  const id = c.req.param('id');
  const body = c.req.valid('json');

  // Fetch existing to merge
  const existing = await db.execute(sql`
    SELECT * FROM "documentTemplates"
    WHERE id = ${id}
      AND "tenantId" = ${tenantId}
    LIMIT 1
  `);

  const row = (existing.rows ?? [])[0] as Record<string, unknown> | undefined;
  if (!row) return c.json({ error: 'Not found' }, 404);

  const newHtmlBody = body.htmlBody ?? String(row['htmlBody'] ?? '');
  const explicitVars = body.variables ?? (row['variables'] as Array<{ name: string; label?: string }>) ?? [];
  const vars = mergeVariables(newHtmlBody, explicitVars);

  const name = body.name ?? String(row['name'] ?? '');
  const type = body.type ?? String(row['type'] ?? '');
  const description = body.description !== undefined ? body.description : (row['description'] as string | null) ?? null;
  const isDefault = body.isDefault !== undefined ? body.isDefault : Boolean(row['isDefault']);

  const result = await db.execute(sql`
    UPDATE "documentTemplates"
    SET
      name = ${name},
      type = ${type},
      description = ${description},
      "htmlBody" = ${newHtmlBody},
      variables = ${JSON.stringify(vars)}::jsonb,
      "isDefault" = ${isDefault},
      "updatedAt" = now()
    WHERE id = ${id}
      AND "tenantId" = ${tenantId}
    RETURNING *
  `);

  const updated = (result.rows ?? [])[0];
  if (!updated) return c.json({ error: 'Update failed' }, 500);
  return c.json(updated);
});

// DELETE /document-templates/:id
documentTemplatesRouter.delete('/:id', async (c) => {
  const { db, tenantId } = c.get('tenantCtx');
  const id = c.req.param('id');

  const result = await db.execute(sql`
    DELETE FROM "documentTemplates"
    WHERE id = ${id}
      AND "tenantId" = ${tenantId}
    RETURNING id
  `);

  if ((result.rows ?? []).length === 0) return c.json({ error: 'Not found' }, 404);
  return c.json({ deleted: true, id });
});

// ── Template rendering ─────────────────────────────────────────

const renderSchema = z.object({
  variables: z.record(z.string(), z.string()),
  name: z.string().min(1),
  entityType: z.string().optional(),
  entityId: z.string().optional(),
});

// POST /document-templates/:id/render
documentTemplatesRouter.post('/:id/render', zValidator('json', renderSchema), async (c) => {
  const { db, tenantId, identityId } = c.get('tenantCtx');
  const templateId = c.req.param('id');
  const body = c.req.valid('json');

  // Load template
  const tplResult = await db.execute(sql`
    SELECT * FROM "documentTemplates"
    WHERE id = ${templateId}
      AND "tenantId" = ${tenantId}
    LIMIT 1
  `);

  const tpl = (tplResult.rows ?? [])[0] as Record<string, unknown> | undefined;
  if (!tpl) return c.json({ error: 'Template not found' }, 404);

  // Substitute variables
  const htmlBody = String(tpl['htmlBody'] ?? '');
  const substituted = substituteVariables(htmlBody, body.variables);

  // Wrap in full HTML document
  const htmlOutput = wrapHtml(body.name, substituted);

  // Save to generatedDocuments
  const saveResult = await db.execute(sql`
    INSERT INTO "generatedDocuments" (
      "tenantId", "templateId", name, variables, "htmlOutput",
      "entityType", "entityId", "createdBy"
    ) VALUES (
      ${tenantId},
      ${templateId},
      ${body.name},
      ${JSON.stringify(body.variables)}::jsonb,
      ${htmlOutput},
      ${body.entityType ?? null},
      ${body.entityId ?? null},
      ${identityId ?? null}
    )
    RETURNING id, name
  `);

  const saved = (saveResult.rows ?? [])[0] as Record<string, unknown> | undefined;
  if (!saved) return c.json({ error: 'Failed to save generated document' }, 500);

  return c.json({ id: saved['id'], name: saved['name'], htmlOutput }, 201);
});
