import { Hono } from 'hono';
import { sql } from 'drizzle-orm';
import { sharedDb } from '../shared.js';
import type { TenantContext } from '../middleware/tenant-context.js';

const invoiceEmailRouter = new Hono<{ Variables: TenantContext }>();

// GET /preview/:invoiceId — generate HTML invoice
invoiceEmailRouter.get('/preview/:invoiceId', async (c) => {
  const invoiceId = c.req.param('invoiceId');
  const { tenantId } = c.get('tenantCtx');

  const db = sharedDb;
  const result = await db.execute(sql`
    SELECT * FROM "entityRecords"
    WHERE id = ${invoiceId}::uuid AND "tenantId" = ${tenantId} AND "entityType" = 'Invoice'
  `);
  const invoice = result.rows?.[0];
  if (!invoice) return c.json({ error: 'Not found' }, 404);

  const d = invoice.data as Record<string, unknown>;
  const html = generateInvoiceHtml({
    number: d.number as string ?? 'INV-0001',
    customerName: d.customerName as string ?? 'Customer',
    amount: Number(d.amount ?? 0),
    currency: d.currency as string ?? 'USD',
    status: d.status as string ?? 'draft',
    dueDate: d.dueDate as string,
    lineItems: (d.lineItems as any[]) ?? [],
    createdAt: (invoice as Record<string, unknown>)['createdAt'] as string,
  });

  return c.html(html);
});

// POST /send/:invoiceId — send invoice via email (uses @veska/notifications)
invoiceEmailRouter.post('/send/:invoiceId', async (c) => {
  const invoiceId = c.req.param('invoiceId');
  const { tenantId = 'demo', toEmail } = await c.req.json();

  if (!toEmail) return c.json({ error: 'toEmail required' }, 400);

  const db = sharedDb;
  const result = await db.execute(sql`
    SELECT * FROM "entityRecords"
    WHERE id = ${invoiceId}::uuid AND "tenantId" = ${tenantId}
  `);
  const invoice = result.rows?.[0];
  if (!invoice) return c.json({ error: 'Not found' }, 404);

  const d = invoice.data as Record<string, unknown>;

  try {
    const { sendEmail } = await import('@veska/notifications');
    await sendEmail({
      event: 'invoice.sent',
      tenantId,
      title: `Invoice ${d.number ?? ''} from Veska`,
      body: `Please find your invoice for $${d.amount ?? 0} attached. Due date: ${d.dueDate ?? 'N/A'}.`,
      data: { invoiceId, amount: d.amount, dueDate: d.dueDate },
    }, {
      type: 'email',
      enabled: true,
      toEmail,
      resendApiKey: process.env.RESEND_API_KEY,
    });
    return c.json({ success: true, sentTo: toEmail });
  } catch (err) {
    return c.json({ error: String(err) }, 500);
  }
});

function generateInvoiceHtml(invoice: {
  number: string; customerName: string; amount: number; currency: string;
  status: string; dueDate?: string; lineItems: any[]; createdAt: string;
}): string {
  const currencySymbol = invoice.currency === 'EUR' ? '€' : invoice.currency === 'GBP' ? '£' : '$';
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  body { font-family: -apple-system, sans-serif; max-width: 700px; margin: 40px auto; color: #111; }
  .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
  .logo { font-size: 24px; font-weight: 700; }
  .badge { background: ${invoice.status === 'paid' ? '#dcfce7' : '#fef3c7'}; color: ${invoice.status === 'paid' ? '#15803d' : '#92400e'}; padding: 4px 12px; border-radius: 20px; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; margin: 24px 0; }
  th { text-align: left; padding: 8px; background: #f9fafb; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
  td { padding: 10px 8px; border-bottom: 1px solid #f3f4f6; }
  .total { font-size: 20px; font-weight: 700; text-align: right; margin-top: 16px; }
</style></head><body>
  <div class="header">
    <div><div class="logo">Veska</div><div style="color:#888;font-size:13px;margin-top:4px">Invoice</div></div>
    <div style="text-align:right">
      <div style="font-size:22px;font-weight:700">${invoice.number}</div>
      <span class="badge">${invoice.status.toUpperCase()}</span>
    </div>
  </div>
  <div style="margin-bottom:24px">
    <div style="font-size:13px;color:#888">Bill to</div>
    <div style="font-size:16px;font-weight:600">${invoice.customerName}</div>
  </div>
  <table>
    <thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead>
    <tbody>
      ${invoice.lineItems.length ? invoice.lineItems.map((li: any) => `
        <tr><td>${li.description ?? ''}</td><td>${li.quantity ?? 1}</td><td>${currencySymbol}${li.unitPrice ?? 0}</td><td>${currencySymbol}${((li.quantity ?? 1) * (li.unitPrice ?? 0)).toFixed(2)}</td></tr>
      `).join('') : `<tr><td colspan="4" style="color:#888">No line items</td></tr>`}
    </tbody>
  </table>
  <div class="total">Total: ${currencySymbol}${invoice.amount.toFixed(2)}</div>
  ${invoice.dueDate ? `<div style="margin-top:16px;font-size:13px;color:#888">Due date: ${invoice.dueDate}</div>` : ''}
  <div style="margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#aaa">
    Generated by Veska ERP · ${new Date(invoice.createdAt).toLocaleDateString()}
  </div>
</body></html>`;
}

export { invoiceEmailRouter };
